### ISSUE TITLE
'tools' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ghost** [ratsan/dex2c#13]
I'm getting this error protecting my simple app. It says that tools is not recognized, but what tools excatly? I have NDK, apktool and required dependencies installed

I'm using Windows 11 23h2 with Python 3.11.6 installed

```
make: Entering directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
[armeabi-v7a] Install        : libstub.so => libs/armeabi-v7a/libstub.so
make: Leaving directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
make: Entering directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
[arm64-v8a] SharedLibrary  : libstub.so
make: Leaving directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
make: Entering directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
[arm64-v8a] Install        : libstub.so => libs/arm64-v8a/libstub.so
make: Leaving directory 'F:/Github/dex2c/.tmp/dcc-project-6umijLvV'
'tools' is not recognized as an internal or external command,
operable program or batch file.
[ERROR   ] dcc: Compile H:\apptest.apk failed!
Traceback (most recent call last):
  File "F:\Github\dex2c\dcc.py", line 1017, in <module>
    dcc_main(
  File "F:\Github\dex2c\dcc.py", line 786, in dcc_main
    decompiled_dir = ApkTool.decompile(apkfile)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Github\dex2c\dcc.py", line 116, in decompile
    check_call([APKTOOL2, 'd', '-r', '-f', '-o', outdir, apk])
  File "D:\Python3\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tools/apktool.bat', 'd', '-r', '-f', '-o', '.tmp\\dcc-apktool-eLRN6Og0', 'H:\\apptest.apk']' returned non-zero exit status 1.
Command '['tools/apktool.bat', 'd', '-r', '-f', '-o', '.tmp\\dcc-apktool-eLRN6Og0', 'H:\\apptest.apk']' returned non-zero exit status 1.
[INFO    ] dcc: Restoring jni folder
[INFO    ] dcc: Removing .tmp folder
```

**Comment by adhksosne** [comment]
bro, have you solved it?

**Comment by lry127** [comment]
If running on Windows, the file seperator is `//`,  you can try the helper methods provided by the os.path lib.
```
APKTOOL = os.path.join( "F:\Github\dex2c\tools\apktool.jar" )
```
P.S. I don't have a Windows OS to try it now by my self, but it should work.

**Comment by adhksosne** [comment]
> > bro, have you solved it?
> 
> My bad, it wasn't actually solved. I'll leave it open again

I solved the problem by changing "\" to "/" and it didn't seem to be affected by backslashes.
